name: EPG Update

on:
  push:
  schedule:
    - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: EPG Update
      run: |
        rm -f e.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
        git config --global user.name 0sty
        git config --global user.email gougoo2010@gmai.com
        git add e.xml
        git commit -m "Update EPG.xml"
        git push -f origin Grey
