name: EPG Update

on:
  push:
  schedule:
    - cron: 0 * * * *

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: EPG Update
      run: |
        rm -f EPG.xml && wget https://epg.112114.xyz/pp.xml -O EPG.xml
        git config --global user.name actions-user
        git config --global user.email gougoo@foxmail.com
        git add EPG.xml
        git commit -m "Update EPG.xml"
        git push -f origin main
